devices:
  bgp:
    bgp_as_number: ''
    bgp_router_id: ''
    enabled: false
    neighbor_ipv4: ''
    neighbor_ipv6: ''
    network_ipv4: ''
    network_ipv6: ''
    remote_as: ''
  device_info:
    hostname: R1
    mgmt_ip: 10.100.0.6
    password: admin
    username: admin
  interfaces:
  - ip_address: 123.123.123.123/24
    ipv6_address: 2100::2/64
    name: Ethernet1.10
    sub_intf: true
    vlan: '10'
  ospf:
    enabled: false
    networks: []
    ospf_area: ''
    ospf_process: ''
    ospf_router_id: ''
