# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    steps:
      - name: Stage 0 Install packages
        run: pip3 install netmiko napalm ansible

      - name: Stage 1 Check and Fixing Violations 
        run: |
          echo Checking for errors......
          pylint --fail-under=5 /home/student/Documents/CSCI5840_Advanced_Network_Automation/Lab4/playbookCreation.py

      - name: Stage 2 Unit Test Basic Network Connectivity
        run: |
          echo Testing......
          python3 /home/student/Documents/CSCI5840_Advanced_Network_Automation/Lab4/github_actions.py

      - name: Stage 3 Unit Test Code Coverage of Automation Code
        run: |
          echo Testing......
          python3 /home/student/Documents/CSCI5840_Advanced_Network_Automation/Lab7/unit_tests.py


