# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4
      
      # Runs a single command using the runners shell
      - name: Stage 0 Install packages
        run: pip3 install netmiko napalm ansible

      # Runs a set of commands using the runners shell
      - name: Stage 1 Check and Fixing Violations 
        run: |
          echo Checking for errors......
          pylint --fail-under=5 /home/student/Documents/CSCI5840_Advanced_Network_Automation/Lab4/playbookCreation.py

      - name: Stage 2 Unit Test
        run: |
          echo Testing......
          python3 /home/student/Documents/CSCI5840_Advanced_Network_Automation/Lab4/github_actions.py

